#!/bin/bash

cd ~/repos/App/Tomcat_PA/WebRoot/WEB-INF/classes/com/peopleAnswers/ws/messages/

cp enwisenhrsd/WsMessageBehavioralReportEncapEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestErrorResponseEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourUpdateResponseEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourUpdateEncapEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen$StatisticType.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen$ItemType.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageBehavioralReportResponseEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen$RunType.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen$ContentType.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageVendorCheckOrderTourStatusRequestEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen$StatType.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageVendorCheckOrderTourStatusResponseSuccessEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen$MessageType.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageBehavioralReportEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourRequestResponseEnwisen$ErrorInfoType.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp enwisenhrsd/WsMessageTourUpdateEnwisen.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobpartners/WsMessageAssessmentOrderRequestJobPartners.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobpartners/WsMessageAssessmentOrderAcknowledgementJobPartners.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckSSOErrorResponseHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckOrderUpdateErrorResponseHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckOrderUpdateSuccessResponseHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckOrderSuccessResponseHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckSSORequestHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckOrderUpdateRequestHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckSSOSuccessResponseHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckOrderRequestHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hireright/WsMessageVendorCheckOrderErrorResponseHireRight.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp peopleclick/WsMessageAssessmentOrderAcknowledgementPeopleclick.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp peopleclick/WsMessageAssessmentOrderRequestPeopleclick.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp knowbase/WsMessageVendorCheckOrderRequestKnowbase.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp knowbase/WsMessageVendorCheckOrderResponseKnowbase.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adprehire/WsMessageVendorCheckOrderRequestADPRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adprehire/WsMessageVendorCheckOrderResponseADPRehireEncap.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adprehire/WsMessageVendorCheckOrderAlternateMsgResponse.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adprehire/WsMessageVendorCheckOrderResponseADPRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp previsor/WsMessageVendorCheckOrderRequestPreVisor.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp previsor/WsMessageVendorCheckOrderUpdateRequestPreVisor.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp previsor/WsMessageVendorCheckOrderErrorResponsePreVisor.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp previsor/WsMessageVendorCheckOrderUpdateRequestEncapPreVisor.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp previsor/WsMessageVendorCheckOrderResponsePreVisor.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp previsor/WsMessageVendorCheckOrderSuccessResponsePreVisor.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp previsor/WsMessageVendorCheckOrderUpdateResponsePreVisor.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kenexa/WsMessageAssessmentOrderRequestEncapKenexa.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kenexa/WsMessageAssessmentOrderAcknowledgementKenexa.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kenexa/WsMessageAssessmentOrderRequestKenexa.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp michaelsrehire/WsMessageVendorCheckOrderErrorResponseMichaelsRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp michaelsrehire/WsMessageVendorCheckOrderSuccessResponseMichaelsRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp michaelsrehire/WsMessageVendorCheckOrderRequestMichaelsRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp saversoracle/WsMessageAssessmentOrderRequestSaversOracle.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp saversoracle/WsMessageAssessmentOrderAcknowledgementSaversOracle.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/monster/WsMessageJobBoardJobAdErrorResponseMonster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/monster/WsMessageJobBoardJobAdMonster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/monster/WsMessageJobBoardJobAdSuccessResponseMonster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/careerbuilderlpi/WsMessageJobBoardJobAdResponseCareerBuilderLPI.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/careerbuilderlpi/WsMessageJobBoardJobAdCareerBuilderLPI.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/linkedin/WsMessageJobBoardJobAdLinkedIn.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/linkedin/WsMessageJobBoardJobAdErrorResponseLinkedIn.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/xmlposting/WsMessageJobBoardJobPostingXml.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/xmlposting/WsMessageJobBoardPostingXmlBroadBean.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/hcareers/WsMessageJobBoardJobAdHCareers.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/tmpjobdistribution/WsMessageEncapTmpJobDistribution.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/tmpjobdistribution/WsMessageJobBoardJobAdErrorResponseTMPJobDistribution.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/tmpjobdistribution/WsMessageJobBoardJobAdTMPJobDistribution.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp jobboard/tmpjobdistribution/WsMessageJobBoardJobAdSuccessResponseTMPJobDistribution.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kronos_vii/WsMessageAssessmentOrderAcknowledgementKronosVii.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kronos_vii/WsMessageAssessmentOrderRequestKronosVii.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckOrderUpdateErrorResponseSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckAdverseActionRequestSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckSSOErrorResponseSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckOrderSuccessResponseSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckSSOSuccessResponseSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckOrderUpdateRequestSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckOrderRequestSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckOrderErrorResponseSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckSSORequestSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckAdverseActionResponseSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sterling/WsMessageVendorCheckOrderUpdateSuccessResponseSterling.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp brookstone/WsMessageVendorCheckOrderResponseBrookstoneWageVerify.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp servicemasterhiremessage/WsMessageVendorCheckOrderSuccessResponseServiceMasterHireMessage.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp servicemasterhiremessage/WsMessageVendorCheckOrderErrorResponseServiceMasterHireMessage.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp servicemasterhiremessage/WsMessageVendorCheckOrderRequestServiceMasterHireMessage.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp dunkin/WsMessageAssessmentOrderRequestDunkin.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp dunkin/WsMessageAssessmentOrderAcknowledgementDunkin.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp dillardsonboarding/WsMessageVendorCheckOrderNewHireResultDillardsNewHire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp dillardsonboarding/WsMessageVendorCheckOrderNewHireRequestDillardsNewHire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp workday/WsMessageVendorCheckOrderErrorResponseWorkday.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp workday/WsMessageVendorCheckOrderRequestWorkday.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp workday/WsMessageVendorCheckOrderSuccessResponseWorkday.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp silkroad/WsMessageAssessmentStatusAcknowledgementSilkRoad.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp silkroad/WsMessageAssessmentOrderAcknowledgementSilkRoad.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp silkroad/WsMessageAssessmentOrderRequestSilkRoad.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp silkroad/WsMessageAssessmentStatusRequestSilkRoad.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp pereless/WsMessageAssessmentOrderRequestPereless.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp pereless/WsMessageAssessmentStatusRequestPereless.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp pereless/WsMessageAssessmentOrderAcknowledgementPereless.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp pereless/WsMessageAssessmentStatusAcknowledgementPereless.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageResumeUploadResponseMonster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageResumeUploadResponseMonsterErrorAlternate.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageMonsterCommonHeader.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageResumeUploadResponseMonsterError.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageApplicationUploadResponseMonsterError.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageApplicationUploadResponseMonster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageApplicationUploadMonster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp monster/WsMessageResumeUploadMonster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp incomingsso/WsMessageIncomingSSOResponse.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp incomingsso/WsMessageIncomingSSORequest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp performanceassociates/WsMessageVendorCheckOrderAssessmentResultPerformanceAssociates.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp performanceassociates/WsMessageVendorCheckOrderAssessmentAcknowledgementPerformanceAssociates.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp performanceassociates/WsMessageVendorCheckOrderAssessmentOrderPerformanceAssociates.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp performanceassociates/WsMessageVendorCheckOrderAssessmentResultAcknowledgementPerformanceAssociates.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckApplicationAcknowledgmentMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckAssessmentOrderAcknowledgmentMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckAssessmentResultMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckHireNoticeMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckAssessmentOrderAcknowledgmentTCSREncapMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckAssessmentOrderSoapErrorMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckAssessmentOrderRequestMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp maximus/WsMessageVendorCheckAssessmentOrderAcknowledgmentTCOREncapMaximus.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hrsmart/WsMessageAssessmentOrderAcknowledgementHRSmart.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hrsmart/WsMessageAssessmentOrderRequestEncapHRSmart.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp hrsmart/WsMessageAssessmentOrderRequestHRSmart.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ultimate/WsMessageAssessmentOrderRequestEncapUltimate.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ultimate/WsMessageAssessmentOrderAcknowledgementUltimate.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ultimate/WsMessageAssessmentOrderRequestUltimate.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderUpdateRequestGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderRequestGISMaster$1.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderDuplicateErrorResponseGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderRequestGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderRequestGISMaster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderUpdateResponseGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckUpdateRequestEncapGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderErrorResponseGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderSuccessResponseGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp gis/WsMessageVendorCheckOrderResponseEncapGIS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp frslinxml/WsMessageVendorCheckFrsBgCheckReportsResponseComplete.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp frslinxml/WsMessageVendorCheckFrsBgCheckReportsRequest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp frslinxml/WsMessageVendorCheckFrsBgCheckRequestResponse.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp frslinxml/WsMessageVendorCheckFrsBgCheckReportsResponseResults.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp frslinxml/WsMessageVendorCheckFrsBgCheckRequest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckHireNoticeResponseTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckHireNoticeTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckEligibilityResultsResponseTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckFormsRequestResponseTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckScreeningRequestTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckScreeningRequestResponseTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckEligibilityResultsTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talxwotc/WsMessageVendorCheckFormsRequestTalxWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp belk/WsMessageAssessmentOrderAcknowledgementBelk.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp belk/WsMessageAssessmentOrderRequestBelk.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp usverifyonboarding/WsMessageVendorCheckOrderErrorResponseUSVerifyOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp usverifyonboarding/WsMessageVendorCheckOrderSuccessResponseUSVerifyOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp usverifyonboarding/WsMessageVendorCheckOrderRequestUSVerifyOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp vereda/WsMessageVendorCheckOrderUpdateRequestEncapVereda.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp vereda/WsMessageVendorCheckOrderUpdateSuccessResponseVereda.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp vereda/WsMessageVendorCheckOrderUpdateRequestVereda.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp vereda/WsMessageVendorCheckOrderSuccessResponseVereda.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp vereda/WsMessageVendorCheckOrderErrorResponseVereda.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp vereda/WsMessageVendorCheckOrderUpdateErrorResponseVereda.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp vereda/WsMessageVendorCheckOrderRequestVereda.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ess/WsMessageVendorCheckOrderUpdateRequestESS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ess/WsMessageVendorCheckOrderSuccessResponseESS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ess/WsMessageVendorCheckOrderRequestESS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ess/WsMessageVendorCheckOrderErrorResponseESS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ess/WsMessageVendorCheckOrderUpdateErrorResponseESS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ess/WsMessageVendorCheckOrderUpdateSuccessResponseESS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp transunion/WsMessageVendorCheckOrderAlternateErrorResponseTransUnion.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp transunion/WsMessageVendorCheckOrderRequestTransUnion.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp transunion/WsMessageVendorCheckOrderUpdateResponseTransUnion.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp transunion/WsMessageVendorCheckOrderResponseTransUnion.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp transunion/WsMessageVendorCheckOrderResponseTransUnion$Field.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp transunion/WsMessageVendorCheckOrderResponseEncapTransUnion.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp transunion/WsMessageVendorCheckOrderUpdateRequestTransUnion.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderUpdateRequestSutherlandPhase3.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$LanguageCd.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$MeetsAgeRequirment.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderFaultResponseSutherlandPhase3$IBResponseList.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$Compensation$CurrencyCode.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$Compensation.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderAlternateResponseSutherlandPhase3.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$ORGRelationship.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$ActionReason.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$1.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$HiringAction.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderUpdateResponseSutherlandPhase3.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderSuccessResponseSutherlandPhase3.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$Gender.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderFaultResponseSutherlandPhase3.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland_phase3/WsMessageVendorCheckOrderRequestSutherlandPhase3$Compensation$Frequency.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp WsMessageRestIncoming.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp genericATS/WsMessageAssessmentOrderRequestGeneric.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp genericATS/WsMessageAssessmentOrderAcknowledgementGeneric.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp genericATS/WsMessageAssessmentOrderRequestGenericEncap.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp technomedia/WsMessageAssessmentOrderRequestTechnomedia.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp technomedia/WsMessageAssessmentOrderAcknowledgementTechnomedia.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderExponenthrCreateEanRequest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderExponenthrCreateEanResponse.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderTerminationInfoResponse.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderEmployeeLookupRequest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderTerminationInfoRequest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderExponenthrCreateEanRequest$EANFields.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderEmployeeLookupResponse$EmployeeMatchList.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderEmployeeLookupResponse.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp exponenthr/WsMessageVendorCheckOrderExHRAlternateMsgResponse.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland/WsMessageVendorCheckOrderRequestSutherland.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland/WsMessageEmployeeTerminationResponseSutherland.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland/WsMessageVendorCheckOrderResponseSutherland.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland/WsMessageRequisitionCreationRequestSutherland.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland/WsMessageVendorCheckOrderResponseEncapSutherland.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland/WsMessageEmployeeTerminationRequestSutherland.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp sutherland/WsMessageRequisitionCreationResponseSutherland.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp alexlee/WsMessageEmployeeTerminationRequestAlexLee.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp alexlee/WsMessageEmployeeTerminationResponseAlexLee.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp alexlee/WsMessageVendorCheckOrderResponseAlexLee.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp alexlee/WsMessageVendorCheckOrderRequestAlexLee.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp redcarpetonboarding/WsMessageVendorCheckOrderSuccessResponseRedCarpetOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp redcarpetonboarding/WsMessageVendorCheckOrderErrorResponseRedCarpetOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp redcarpetonboarding/WsMessageVendorCheckOrderRequestRedCarpetOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckHiringSuccessResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckSSOSuccessResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckHiringRequestADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckOrderErrorResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckOrderRequestADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckOrderSuccessResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckSSOErrorResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckOrderUpdateRequestADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckSSORequestADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckOrderUpdateSuccessResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckOrderUpdateErrorResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpwotc/WsMessageVendorCheckHiringErrorResponseADPWOTC.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageLocationSynchKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckLoginResponseKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckOrderResponseEncapKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckLoginFoundationResponseKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckOrderRequestKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckOrderUpdateRequestKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckLoginFoundationRequestKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageGeographyExportItemKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckLoginResponseEncapKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageUserSynchResponseKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckOrderUpdateResponseKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckOrderResponseKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckLoginRequestKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageUserSynchResponseEncapKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageVendorCheckLoginFoundationResponseEncapKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kms/WsMessageUserSynchRequestKMS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp s3hrmhire/WsMessageSuccessResponseS3HrmHire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp s3hrmhire/WsMessageErrorResponseS3HrmHire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckOrderRequestQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckOrderSuccessResponseQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckSSORequestQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckOrderErrorResponseQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckOrderUpdateErrorResponseQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckSSOSuccessResponseQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckSSOErrorResponseQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckOrderUpdateSuccessResponseQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp quest/WsMessageVendorCheckOrderUpdateRequestQuest.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageLoginRequestTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageUpdateCandidateRequestTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageLogoutRequestTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageLogoutResponseTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageLoginResponseTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageUpdateCandidateResponseTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageGetURLRequestTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageCandidateTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageGetURLResponseTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageGetCandidateByIdRequestTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp tbe/WsMessageGetCandidateByIdResponseTBE.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorAdminOperationRefreshSystemPasswordErrorResponseChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorAdminOperationRefreshSystemPasswordRequestChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorCheckOrderUpdateRequestChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorCheckOrderRequestChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorCheckOrderUpdateErrorResponseChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorCheckOrderSuccessResponseChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorCheckOrderErrorResponseChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorAdminOperationRefreshSystemPasswordSuccessResponseChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp choicepoint/WsMessageVendorCheckOrderUpdateSuccessResponseChoicePoint.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp virtualedge/WsMessageAssessmentOrderRequestVirtualEdge.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp virtualedge/WsMessageAssessmentOrderRequestEncapVirtualEdge.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp virtualedge/WsMessageAssessmentOrderAcknowledgementVirtualEdge.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckOrderSuccessResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckOrderRequestTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckOrderUpdateErrorResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorSSORequestTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckSSORequestTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckOrderRequestTalx$1.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckOrderUpdateRequestTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckSSOErrorResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorSSOAsCandidateRequestTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckOrderErrorResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorSSOSuccessResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorSSOErrorResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckSSOSuccessResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talx/WsMessageVendorCheckOrderUpdateSuccessResponseTalx.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp dillardsrehire/WsMessageVendorCheckOrderSuccessResponseDillardsRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp dillardsrehire/WsMessageVendorCheckOrderRequestDillardsRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp dillardsrehire/WsMessageVendorCheckOrderErrorResponseDillardsRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp snaphire/WsMessageAssessmentOrderAcknowledgementSnaphire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp snaphire/WsMessageAssessmentOrderRequestSnaphire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentwise/WsMessageVendorCheckApplicantStatusTalentwise.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentwise/WsMessageVendorCheckApplicantStatusResponseTalentwise.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentwise/WsMessageVendorCheckApplicantCheckResponseTalentwise.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentwise/WsMessageVendorCheckApplicantCheckTalentwise.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp atlantis/WsMessageAssessmentOrderAcknowledgementAtlantis.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp atlantis/WsMessageAssessmentOrderRequestAtlantis.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp lexisnexisforeground/WsMessageVendorCheckOrderSuccessResponseLexisNexisForeground.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp lexisnexisforeground/WsMessageVendorCheckOrderRequestLexisNexisForeground.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp lexisnexisforeground/WsMessageVendorCheckOrderErrorResponseLexisNexisForeground.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp lexisnexisforeground/WsMessageVendorCheckOrderUpdateRequestLexisNexisForeground.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp lexisnexisforeground/WsMessageVendorCheckOrderUpdateSuccessResponseLexisNexisForeground.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp lexisnexisforeground/WsMessageVendorCheckOrderUpdateErrorResponseLexisNexisForeground.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp liberty/WsMessageVendorCheckOrderUpdateErrorResponseLiberty.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp liberty/WsMessageVendorCheckOrderUpdateSuccessResponseLiberty.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp liberty/WsMessageVendorCheckOrderUpdateRequestLiberty.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp liberty/WsMessageVendorCheckOrderRequestLiberty.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp liberty/WsMessageVendorCheckOrderMessageResponseLiberty.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/DimensionReportBuildExtra.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageAssessmentScienceRequestTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageAssessmentOrderAcknowledgementTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageAssessmentOrderRequestTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageRequisitionCreationResponseTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageUpdateCandidateRequestTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageAssessmentStatusAcknowledgementTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageAssessmentStatusRequestTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageAssessmentScienceDataResponseTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/DimensionReportBuildMuscle.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp talentmanagement/WsMessageRequisitionCreationRequestTalentManagement.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp michaelsonboarding/WsMessageVendorCheckOrderSuccessResponseMichaelsOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp michaelsonboarding/WsMessageVendorCheckOrderErrorResponseMichaelsOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp michaelsonboarding/WsMessageVendorCheckOrderRequestMichaelsOnboarding.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kronos/WsMessageAssessmentOrderRequestKronos.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp kronos/WsMessageAssessmentOrderAcknowledgementKronos.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp greystarrehire/WsMessageVendorCheckOrderResponseGreystarRehire.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ezcorp/WsMessageAssessmentOrderAcknowledgementEzCorp.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ezcorp/WsMessageAssessmentOrderRequestEzCorp.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp snagajob/WsMessageAssessmentOrderAcknowledgementSnagajob.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp snagajob/WsMessageTestCompletionRequestSnagajob.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp snagajob/WsMessageTestCompletionAcknowledgementSnagajob.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp snagajob/WsMessageAssessmentOrderRequestSnagajob.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageVendorCheckOrderSuccessResponseADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageVendorCheckOrderUpdateRequestEncapADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageAdverseActionRequestADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageVendorCheckOrderErrorResponseADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageVendorCheckOrderRequestADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageVendorCheckOrderResponseEncapADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageVendorCheckOrderUpdateResponseADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageVendorCheckOrderUpdateRequestADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageAdverseActionErrorResponseADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adpsass/WsMessageAdverseActionSuccessResponseADPSASS.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp moore/WsMessageVendorCheckOrderRequestMoore.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp moore/WsMessageVendorCheckOrderUpdateErrorResponseMoore.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp moore/WsMessageVendorCheckOrderUpdateSuccessResponseMoore.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp moore/WsMessageVendorCheckOrderSuccessResponseMoore.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp moore/WsMessageVendorCheckOrderUpdateRequestMoore.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp moore/WsMessageVendorCheckOrderErrorResponseMoore.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp moore/WsMessageVendorCheckOrderResponseMooreEncap.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckHireNoticeResponseErrorAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckHireNoticeResponseAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckUpdateWotcResultsResponseAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckUpdateWotcEligibilityResultsAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckUpdateWotcCreditsResultsAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckScreeningRequestResponseAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckScreeningRequestResponseErrorAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckScreeningRequestAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp adppreferredwotc/WsMessageVendorCheckHireNoticeRequestAdpPreferredWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp taxbreakwotc/WsMessageVendorCheckHireNoticeResponseTaxBreakWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp taxbreakwotc/WsMessageVendorCheckHireNoticeTaxBreakWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckAssessmentStatusRequestErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckApplicantUpdateAcknowledgementErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckDocumentOrderRequestErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckAssessmentStatusAcknowledgementPostErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckDocumentOrderAcknowledgementErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckAssessmentOrderRequestErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckAssessmentOrderAcknowledgementErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckApplicantUpdateRequestErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckAssessmentStatusAcknowledgementSoapErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp ernstandyoungwotc/WsMessageVendorCheckUpdateAcknowledgementErnstAndYoungWotc.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp taleo/WsMessageAssessmentStatusAcknowledgementTaleo.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp taleo/WsMessageAssessmentOrderAcknowledgementTaleo.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp taleo/WsMessageAssessmentOrderRequestTaleo.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp taleo/WsMessageAssessmentStatusRequestTaleo.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp successfactorsmaster/WsMessageAssessmentOrderRequestSuccessFactorsMaster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp successfactorsmaster/WsMessageAssessmentOrderAcknowledgementSuccessFactorsMaster.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp successfactors/WsMessageAssessmentOrderAcknowledgementSuccessFactors.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/
cp successfactors/WsMessageAssessmentOrderRequestSuccessFactors.class  ~/repos/App/out/artifacts/Tomcat_PA_war_exploded/WEB-INF/classes/com/peopleAnswers/ws/messages/

