#!/bin/sh
echo "cd to folder..."
cd /Users/estevens/dev/alg-source/dev-environment/uds-server
echo "kill container..."
docker kill hbsi-processor-hotel-supply
echo "rm container"
docker rm hbsi-processor-hotel-supply
