#!/bin/sh
echo "cd to folder..."
cd /Users/estevens/dev/alg-source/dev-environment/uds-server
echo "kill container..."
docker kill hotel-supply
echo "rm container"
docker rm hotel-supply
docker rmi alda9lcddkr01.applevac.com/hotel-supply:latest
